export const SEED_ROWS = [
  {
    tenant_id: "tenant-a",
    user_id: "user-1",
    action: "PATIENT_VIEWED",
    resource: "patient/101",
    payload: { department: "cardiology" },
    created_at: "2025-06-01T09:15:00Z",
  },
  {
    tenant_id: "tenant-a",
    user_id: "user-1",
    action: "PATIENT_UPDATED",
    resource: "patient/101",
    payload: { field: "notes" },
    created_at: "2025-06-01T10:30:00Z",
  },
  {
    tenant_id: "tenant-a",
    user_id: "user-2",
    action: "APPOINTMENT_CREATED",
    resource: "appointment/501",
    payload: { duration: 30 },
    created_at: "2025-06-02T08:00:00Z",
  },
  {
    tenant_id: "tenant-a",
    user_id: "user-2",
    action: "REPORT_EXPORTED",
    resource: "report/monthly",
    payload: { format: "pdf" },
    created_at: "2025-06-03T14:45:00Z",
  },
  {
    tenant_id: "tenant-a",
    user_id: "user-1",
    action: "LOGIN",
    resource: "auth/session",
    payload: {},
    created_at: "2025-06-04T07:00:00Z",
  },
  {
    tenant_id: "tenant-a",
    user_id: "user-3",
    action: "PRESCRIPTION_ISSUED",
    resource: "patient/205",
    payload: { medication: "amoxicillin" },
    created_at: "2025-06-05T11:20:00Z",
  },
  {
    tenant_id: "tenant-b",
    user_id: "user-4",
    action: "PATIENT_VIEWED",
    resource: "patient/301",
    payload: { department: "neurology" },
    created_at: "2025-06-01T12:00:00Z",
  },
  {
    tenant_id: "tenant-b",
    user_id: "user-4",
    action: "LAB_RESULT_ADDED",
    resource: "patient/301/lab/12",
    payload: { type: "blood" },
    created_at: "2025-06-02T16:30:00Z",
  },
  {
    tenant_id: "tenant-b",
    user_id: "user-5",
    action: "USER_INVITED",
    resource: "user/509",
    payload: { role: "nurse" },
    created_at: "2025-06-03T09:10:00Z",
  },
  {
    tenant_id: "tenant-b",
    user_id: "user-5",
    action: "SETTINGS_CHANGED",
    resource: "settings/notifications",
    payload: { email: true },
    created_at: "2025-06-04T13:00:00Z",
  },
  {
    tenant_id: "tenant-b",
    user_id: "user-4",
    action: "LOGOUT",
    resource: "auth/session",
    payload: {},
    created_at: "2025-06-05T18:45:00Z",
  },
  {
    tenant_id: "tenant-c",
    user_id: "user-6",
    action: "PATIENT_VIEWED",
    resource: "patient/401",
    payload: { department: "orthopedics" },
    created_at: "2025-06-01T08:30:00Z",
  },
  {
    tenant_id: "tenant-c",
    user_id: "user-6",
    action: "IMAGING_ORDERED",
    resource: "patient/401/imaging",
    payload: { type: "xray" },
    created_at: "2025-06-02T10:15:00Z",
  },
  {
    tenant_id: "tenant-c",
    user_id: "user-7",
    action: "BILLING_UPDATED",
    resource: "billing/invoice/88",
    payload: { amount: 250 },
    created_at: "2025-06-03T15:40:00Z",
  },
  {
    tenant_id: "tenant-c",
    user_id: "user-7",
    action: "NOTE_ADDED",
    resource: "patient/402",
    payload: { visibility: "internal" },
    created_at: "2025-06-04T11:55:00Z",
  },
  {
    tenant_id: "tenant-c",
    user_id: "user-6",
    action: "PATIENT_ARCHIVED",
    resource: "patient/399",
    payload: {},
    created_at: "2025-06-06T09:00:00Z",
  },
] as const;
